### ISSUE TITLE
Add chnode and chpython

### ISSUE THREAD

**Issue by geryogam** [bernardoduarte/awesome-version-managers#4]
The list is missing two awesome version managers:
- [chnode](https://github.com/tkareine/chnode);
- [chpython](https://github.com/kisoku/chpython.git).

See [this post](https://stackoverflow.com/a/74008328/2326961) for more details.

**Comment by bernardoduarte** [comment]
@maggyero Thanks for the suggestions!
It seems chnode is a good call, but chpython hasn't been maintained for 10 years ;/ (perhaps I should add a flag for it dunno 🤔)
Also, following chnode's readme I've rediscovered chruby that already is in this list ;D

**Comment by maggyero** [comment]
Welcome.

Yes unfortunately chpython has not been maintained for years (maybe because it is so simple), but it works like a charm.

**Comment by geryogam** [comment]
> Thanks for the suggestions!

Welcome.

> It seems chnode is a good call, but chpython hasn't been maintained for 10 years ;/

Yes unfortunately `chpython` has not been maintained for years, perhaps because it is so simple, but it works like a charm.

The big advantage of `ch*` tools (`chruby`, `chnode`, `chpython`) over `*vm` tools (`rvm`, `nvm`) and `*env` tools (`rbenv`, `nodenv`, `pyenv`) is that they are extremely lightweight, that is why they are the recommended tools. They optionally support *auto-switching* the interpreter version based on the nearest .*-version file (.ruby-version, .node-version, .python-version) by updating the `PATH` environment variable before each execution of a shell command with a function hooked into the shell with `preexec_functions` for Zsh and `PROMPT_COMMAND` for Bash. The other tools use heavier auto-switching strategies: `*vm` tools update `PATH` by redefining `cd`; `*env` tools use a proxy interpreter command (`ruby`, `node`, `python`), called a *shim*, mapping to the right interpreter version.
