### ISSUE TITLE
Add frum to Ruby

### ISSUE THREAD

**Issue by naxels** [bernardoduarte/awesome-version-managers#5]
Hi, thank you for compiling this list!

Here's a suggestion to add to Ruby: frum, https://github.com/TaKO8Ki/frum

It's a simple & light weight Ruby version manager I've been using for at least a year
and has not let me down.

Thank you

**Comment by bernardoduarte** [comment]
@naxels Thanks for the suggestion!
I've just looked it up and it looks a really cool project, just added to the list ;D
